version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./portainer/etc/localtime:/etc/localtime:ro
      - ./portainer/var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer/data:/data
    ports:
      - 9000:9000
    networks:
      - home-network

  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    volumes:
      - ./dashy/conf.yml:/app/public/conf.yml
    env_file:
      - ./dashy/.env
    ports:
      - 4000:80
    networks:
      - home-network
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    env_file:
      - ./dashy/.env
    volumes:
      - ./node-red/data:/data
    ports:
      - 1880:1880
    networks:
      - home-network

networks:
  home-network:
    