version: '3.9'

services:
  #Grafana: Done
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana:/var/lib/grafana
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    environment:
      - PROMETHEUS_DB_URL=${PROMETHEUS_DB_URL}
    volumes:
      - ./prometheus:/etc/prometheus

  #InfluxDB: Done
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  #MQTT: Done
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: always
    depends_on:
      - postgres
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant:/config
    environment:
      - HA_DB_URL=${HA_DB_URL}

  #Node-Red: Done
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    environment:
      - TZ=${GENERIC_TIMEZONE}

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${HA_DB_NAME},${PROM_DB_NAME},${NC_DB_NAME}
      - POSTGRES_USER=${HA_DB_USER},${PROM_DB_USER},${NC_DB_USER}
      - POSTGRES_PASSWORD=${HA_DB_PASSWORD},${PROM_DB_PASSWORD},${NC_DB_PASSWORD}

  # Utilities
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    ports:
      - "3000:3000"
  
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: always
    ports:
      - "4000:80"
  
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: always
    ports:
      - "5000:8080"
    environment:
      - APP_LOCALE=${APP_LOCALE}
      - APP_NAVBAR_NAME=Stirling pdf
      - APP_ROOT_PATH=/
        
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./linkding:/etc/linkding/data

  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: always
    ports:
      - "4080:80"
    volumes:
      - ./dashy/conf.yml:/app/public/conf.yml

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/d–∞ta:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./uptime-kuma:/app/data
  
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
  
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_DB_URL=${NEXTCLOUD_DB_URL}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      - ./nextcloud-data:/var/www/html

  
       
        
              
